BikeLogic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Homepage.urls')),
    path('user_profile/', include('Userprofile.urls')),
    path('Delivery/', include('Delevery.urls')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Delevery/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views


app_name = 'Delivery'


urlpatterns = [

    path('delivery', views.post_delivery, name='posy_delivery'),
    path('Jobs', views.jobs, name='jobs'),
    path('success', views.order_received, name='success'),
    path('single/<int:id>', views.single, name='single'),
    path('search', views.search, name='search'),
    path('update/<int:id>', views.update, name='update'),

]

templates/Delivery/Jobs.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Posts {% endblock %}

{% block content %}

    <!-- ***** Blog Area Start ***** -->
    <section class="blog-area load-more">
        <div class="container">
            <div class="row items">
                {% for datum in page %}

                    <div class="col-12 col-md-4 item">
                        <!-- Single Blog -->
                        <div class="card blog-card">

                            <div class="blog-content">
                                <!-- Meta Info -->
                                <ul class="meta-info d-flex justify-content-between list-unstyled mt-4">
                                    <li>By: <a class="p-2">{{ datum.by }}</a></li>
                                    {#                                    <li><a href="#">Feb 19, 2021</a></li>#}
                                </ul>
                                <!-- Blog Title -->
                                <a href="{% url 'Delivery:single' datum.id %}">
                                    <h4>{{ datum.title }}</h4>
                                </a>
                                <p>{{ datum.type }}</p>
                                <!-- Blog Button -->
                                <a class="btn content-btn" href="{{ datum.url }}" target="_blank">Go to</a>
                                {#                                <p>{{ datum.id }}</p>#}
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>

            <nav aria-label="..." class="col-12 text-center">
                <ul class="pagination pagination-sm">
                    {% if page.has_previous %}
                        <li class="page-item"><a class="btn btn-bordered-white mt-5" href="?page={{ page.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="btn btn-bordered-white mt-5 disabled">Previous</a></li>
                    {% endif %}

                    {% if page.has_previous %}
                        <li class="page-item"><a class="btn btn-bordered-white mt-5" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a>
                        </li>
                    {% endif %}

                    <li class="page-item active" aria-current="page">
                      <span class="btn btn-bordered-white mt-5">
                        {{ page.number }}
                        <span class="sr-only active">(current)</span>
                      </span>

                    {% if page.has_next %}
                        <li class="page-item"><a class="btn btn-bordered-white mt-5" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a>
                        </li>
                    {% endif %}

                    {% if page.has_next %}
                        <li class="page-item"><a class="btn btn-bordered-white mt-5" href="?page={{ page.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="btn btn-bordered-white mt-5 disabled">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
            {#                <div class="row">#}
            {#                    <div class="col-12 text-center">#}
            {#                        <a id="load-btn" class="btn btn-bordered-white mt-5" href="#">Load More</a>#}
            {#                    </div>#}
            {#                </div>#}
        </div>
    </section>
    <!-- ***** Blog Area End ***** -->

{% endblock %}

templates/Delivery/search-page.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Search {% endblock %}

{% block content %}

        <!-- ***** Hero Area Start ***** -->
        <section class="hero-section">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-7">
                        <span>Bike Logic</span>
                        <h1 class="mt-4">Order Received</h1>
                        <p>We will get in contact </p>
                        <!-- Buttons -->
                        {% if user.is_authenticated %}
                        <div class="button-group">
{#                            <a class="btn btn-bordered-white" href="explore-1.html"><i class="icon-rocket mr-2"></i>Explore</a>#}
                            <a class="btn btn-bordered-white" href="{% url 'Delivery:posy_delivery' %}"><i class="icon-note mr-2"></i>Create</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Shape -->
            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 465" version="1.1">
                    <defs>
                        <linearGradient x1="49.7965246%" y1="28.2355058%" x2="49.7778147%" y2="98.4657689%" id="linearGradient-1">
                            <stop stop-color="rgba(69,40,220, 0.15)" offset="0%" />
                            <stop stop-color="rgba(87,4,138, 0.15)" offset="100%" />
                        </linearGradient>
                    </defs>
                    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="" fill="url(#linearGradient-1)">
                            <animate id="graph-animation" xmlns="http://www.w3.org/2000/svg" dur="2s" repeatCount="" attributeName="points" values="0,464 0,464 111.6,464 282.5,464 457.4,464 613.4,464 762.3,464 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,323.3 282.5,373 457.4,423.8 613.4,464 762.3,464 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,336.6 457.4,363.5 613.4,414.4 762.3,464 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,323.3 613.4,340 762.3,425.6 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,290.4 762.3,368 912.3,446.4 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,329.6 912.3,420 1068.2,427.6 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,402.4 1068.2,373 1191.2,412 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,336.6 1191.2,334 1328.1,404 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,282 1328.1,314 1440.1,372.8 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,204 1328.1,254 1440.1,236 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,204 1328.1,164 1440.1,144.79999999999998 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,204 1328.1,164 1440.1,8 1440.1,464 0,464;" fill="freeze" />
                        </polygon>
                    </g>
                </svg>
            </div>
		</section>
        <!-- ***** Hero Area End ***** -->

{% endblock %}

templates/Delivery/single-post.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ data.title }} {% endblock %}

{% block content %}

        <!-- ***** Hero Area Start ***** -->
        <section class="single featured post-details">
            <div class="container">
                <div class="row">
                    <!-- Main -->
                    <div class="col-12 col-lg-8 p-0">
                        <div class="row">
                            <div class="col-12 align-self-center">
                                <!-- Image -->
                                <div class="blog-thumb">
                                    <img class="w-100" src="assets/img/blog/blog_single.jpg" alt="">
                                </div>
                                <h2 class="featured ml-0">{{ data.title }}</h2>
                                <p>By: {{ data.by }}</p>
                                <p>Type: {{ data.type }}</p>
                                <a href="{{ data.url }}" target="_blank"><p>Go to</p></a>
                                <a href="{% url 'Delivery:update' data.id %}"><p>Edit</p></a>
{#                                <blockquote>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quam tortor, ultrices accumsan mauris eget, pulvinar tincidunt erat. Sed nisi nisi, rutrum sit amet elit.</blockquote>#}
{#                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. There live the blind texts. Separated they live in right at the coast, a large language ocean. Sed nisi nisi, amet, consectetur adipiscing rutrum sit amet elit.</p>#}
{#                                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>#}

                                <!-- Post Holder -->
                                <ul class="mb-5 post-holder">
                                    <li class="post-meta-item">
                                        <div class="date">
                                            <span class="posted-on">Posted On <a href="#" rel="bookmark"><time class="entry-date published updated" datetime="2018-11-01T06:18:46+00:00">{{ data.date }}</time></a></span>
                                        </div>
                                    </li>
                                </ul>

{#                                <!-- Comments -->#}
{#                                <h3 class="comments-reply-text mb-3">Leave a Reply</h3>#}
{#                                <p class="mt-3">Sed mauris nulla, tempor eu est vel, dapibus hendrerit mauris.</p>#}
{#                                <form>#}
{#                                    <fieldset>#}
{#                                        <div class="row">#}
{#                                            <div class="col-12 col-lg-6 input-group p-0 pr-lg-3 mb-3">#}
{#                                                <input type="text" name="name" data-minlength="3" placeholder="Name" required>#}
{#                                            </div>#}
{#                                            <div class="col-12 col-lg-6 input-group p-0 mb-3">#}
{#                                                <input type="email" name="email" data-minlength="3" placeholder="Email" required>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="row">#}
{#                                            <div class="col-12 input-group p-0 mb-3">#}
{#                                                <textarea name="message" data-minlength="3" rows="4" placeholder="Message" required></textarea>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="col-12 input-group p-0">#}
{#                                            <a class="btn btn-bordered-white text-white">POST COMMENT<i class="icon-login ml-2"></i></a>#}
{#                                        </div>#}
{#                                    </fieldset>#}
{#                                </form>#}
                            </div>
                        </div>
                    </div>

                    <!-- Sidebar -->
                    <aside class="col-12 col-lg-4 pl-lg-5 p-0 float-right sidebar">
                        <div class="row">
                            <div class="col-12 align-self-center text-left">

                                <!-- Widget [categories] -->
                                <div class="item widget-categories">
                                    <h4 class="title">Types</h4>
                                    <ul class="list-group list-group-flush">

                                        <li class="list-group-item d-flex justify-content-between align-items-center">
{#                                            <a href="#">Jobs</a>#}
                                            <form class="row" action="{% url 'Delivery:search' %}" method="post">
                                                {% csrf_token %}
                                                <input type="text" value="job" hidden name="keyword">
                                                <button style="background: transparent; border: none; color: white" name="submit" type="submit">Jobs</button>
                                            </form>
                                            <span class="badge circle">{{ job }}</span>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
{#                                            <a href="" onclick=this.form.submit()>Story</a>#}
                                            <form class="row" action="{% url 'Delivery:search' %}" method="post">
                                                {% csrf_token %}
                                                <input type="text" value="story" hidden name="keyword">
                                                <button style="background: transparent; border: none; color: white" name="submit" type="submit">Story</button>
                                            </form>
                                            <span class="badge circle">{{ story }}</span>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
{#                                            <a href="#">Comment</a>#}
                                            <form class="row" action="{% url 'Delivery:search' %}" method="post">
                                                {% csrf_token %}
                                                <input type="text" value="comment" hidden name="keyword">
                                                <button style="background: transparent; border: none; color: white" name="submit" type="submit">Comment</button>
                                            </form>
                                            <span class="badge circle">{{ comment }}</span>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
{#                                            <a href="#">Poll</a>#}
                                            <form class="row" action="{% url 'Delivery:search' %}" method="post">
                                                {% csrf_token %}
                                                <input type="text" value="poll" hidden name="keyword">
                                                <button style="background: transparent; border: none; color: white" name="submit" type="submit">Poll</button>
                                            </form>
                                            <span class="badge circle">{{ poll }}</span>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
{#                                            <a href="#">PollOpt</a>#}
                                            <form class="row" action="{% url 'Delivery:search' %}" method="post">
                                                {% csrf_token %}
                                                <input type="text" value="pollopt" hidden name="keyword">
                                                <button style="background: transparent; border: none; color: white" name="submit" type="submit">PollOpt</button>
                                            </form>
                                            <span class="badge circle">{{ pollopt }}</span>
                                        </li>
{#                                        <li class="list-group-item d-flex justify-content-between align-items-center">#}
{#                                            <a href="#">Consulting</a>#}
{#                                            <span class="badge circle">13</span>#}
{#                                        </li>#}

                                    </ul>
                                </div>

                                <!-- Widget [tags] -->
{#                                <div class="item widget-tags">#}
{#                                    <h4 class="title">Popular Types</h4>#}
{##}
{#                                    <a href="" class="badge tag">Jobs</a>#}
{#                                    <a href="" class="badge tag">Story</a>#}
{#                                    <a href="" class="badge tag">Comment</a>#}
{#                                    <a href="" class="badge tag">Poll</a>#}
{#                                    <a href="" class="badge tag">PollOut</a>#}
{#                                    <form class="row badge tag" action="{% url 'Delivery:search' %}" method="post">#}
{#                                        {% csrf_token %}#}
{#                                        <input type="text" value="pollopt" hidden name="keyword">#}
{#                                        <button style="background: transparent; border: none; color: white" name="submit" type="submit">PollOpt</button>#}
{#                                    </form>#}
{#                                    <a href="" class="badge tag">WordPress</a>#}
{#                                    <a href="" class="badge tag">Development</a>#}
{#                                    <a href="" class="badge tag">Industry</a>#}
{##}
{#                                </div>#}

                                <!-- Widget [share-this] -->
{#                                <div class="item widget-share-this">#}
{#                                    <h4 class="title">Share This</h4>#}
{#                                    <ul class="navbar-nav social share-list">#}
{##}
{#                                        <li class="nav-item">#}
{#                                            <a href="#" class="nav-link"><i class="icon-social-instagram ml-0"></i></a>#}
{#                                        </li>#}
{#                                        <li class="nav-item">#}
{#                                            <a href="#" class="nav-link"><i class="icon-social-facebook"></i></a>#}
{#                                        </li>#}
{#                                        <li class="nav-item">#}
{#                                            <a href="#" class="nav-link"><i class="icon-social-twitter"></i></a>#}
{#                                        </li>#}
{#                                        <li class="nav-item">#}
{#                                            <a href="#" class="nav-link"><i class="icon-social-linkedin"></i></a>#}
{#                                        </li>#}
{##}
{#                                    </ul>#}
{#                                </div>#}

                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </section>
        <!-- ***** Hero Area End ***** -->

{% endblock %}

templates/Delivery/success.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Success {% endblock %}

{% block content %}

        <!-- ***** Hero Area Start ***** -->
        <section class="hero-section">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-7">
                        <span>Bike Logic</span>
                        <h1 class="mt-4">Order Received</h1>
                        <p>We will get in contact </p>
                        <!-- Buttons -->
                        {% if user.is_authenticated %}
                        <div class="button-group">
{#                            <a class="btn btn-bordered-white" href="explore-1.html"><i class="icon-rocket mr-2"></i>Explore</a>#}
                            <a class="btn btn-bordered-white" href="{% url 'Delivery:posy_delivery' %}"><i class="icon-note mr-2"></i>Create</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Shape -->
            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 465" version="1.1">
                    <defs>
                        <linearGradient x1="49.7965246%" y1="28.2355058%" x2="49.7778147%" y2="98.4657689%" id="linearGradient-1">
                            <stop stop-color="rgba(69,40,220, 0.15)" offset="0%" />
                            <stop stop-color="rgba(87,4,138, 0.15)" offset="100%" />
                        </linearGradient>
                    </defs>
                    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="" fill="url(#linearGradient-1)">
                            <animate id="graph-animation" xmlns="http://www.w3.org/2000/svg" dur="2s" repeatCount="" attributeName="points" values="0,464 0,464 111.6,464 282.5,464 457.4,464 613.4,464 762.3,464 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,323.3 282.5,373 457.4,423.8 613.4,464 762.3,464 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,336.6 457.4,363.5 613.4,414.4 762.3,464 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,323.3 613.4,340 762.3,425.6 912.3,464 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,290.4 762.3,368 912.3,446.4 1068.2,464 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,329.6 912.3,420 1068.2,427.6 1191.2,464 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,402.4 1068.2,373 1191.2,412 1328.1,464 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,336.6 1191.2,334 1328.1,404 1440.1,464 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,282 1328.1,314 1440.1,372.8 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,204 1328.1,254 1440.1,236 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,204 1328.1,164 1440.1,144.79999999999998 1440.1,464 0,464; 0,464 0,367 111.6,263 282.5,282 457.4,263 613.4,216 762.3,272 912.3,376 1068.2,282 1191.2,204 1328.1,164 1440.1,8 1440.1,464 0,464;" fill="freeze" />
                        </polygon>
                    </g>
                </svg>
            </div>
		</section>
        <!-- ***** Hero Area End ***** -->

{% endblock %}