BikeLogic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Homepage.urls')),
    path('user_profile/', include('Userprofile.urls')),
    path('Delivery/', include('Delevery.urls')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Delevery/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views


app_name = 'Delivery'


urlpatterns = [

    path('delivery', views.post_delivery, name='posy_delivery'),
    path('Jobs', views.jobs, name='jobs'),
    path('success', views.order_received, name='success'),
    path('single/<int:id>', views.single, name='single'),
    path('search', views.search, name='search'),
    path('update/<int:id>', views.update, name='update'),

]

Homepage/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views


app_name = 'Homepage'


urlpatterns = [

    path('', views.home, name='home'),

]

Userprofile/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views


app_name = 'userprofile'


urlpatterns = [

    path('login_user', views.LoginView.as_view(), name='login'),
    path('register_user', views.UserCreateView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('user/', views.get_user, name="user_profile"),
    # path('user/update/', views.user_update, name="user_update"),
    # path('change_password_of_user', views.change_password, name='change_a_user_password'),
    # path('change_password_user', views.user_change_password, name='user_password'),

    # reset password
    # path(
    #     'reset_password/',
    #     auth_views.PasswordResetView.as_view(template_name='email-reset.html',
    #                                          success_url=reverse_lazy('userprofile:password_reset_done')),
    #     name='reset_password'),
    #
    # path(
    #     'reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='email-reset-sent.html'),
    #     name='password_reset_done'),
    #
    #
    # path(
    #     'reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(template_name='email-reset-sent.html',
    #                                                 success_url=reverse_lazy('userprofile:password_reset_complete')),
    #     name='password_reset_confirm'),
    #
    #
    # path(
    #     'reset_password_complete/',
    #     auth_views.PasswordResetCompleteView.as_view(template_name='email-reset-done.html'),
    #     name='password_reset_complete'),
]

templates/User/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
        <!-- ***** Breadcrumb Area Start ***** -->
        <section class="breadcrumb-area overlay-dark d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Breamcrumb Content -->
                        <div class="breadcrumb-content text-center">
                            <h2 class="m-0">Login</h2>
                            {{ form.errors }}
                            <ol class="breadcrumb d-flex justify-content-center">
                                <li class="breadcrumb-item"><a href="[{% url 'Homepage:home' %}">Home</a></li>
{#                                <li class="breadcrumb-item"><a href="#">Pages</a></li>#}
                                <li class="breadcrumb-item active">Login</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Breadcrumb Area End ***** -->

        <!-- ***** Login Area Start ***** -->
        <section class="author-area">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-8 col-lg-7">
                        <!-- Intro -->
                        <div class="intro text-center">
                            <span>Login</span>
                            <h3 class="mt-3 mb-0">Login to your Account</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae quo ad iste ipsum officiis deleniti asperiores sit.</p>
                        </div>
                        <!-- Item Form -->
                        <form class="item-form card no-hover" method="post" action="{% url 'userprofile:login' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="email" class="form-control" name="username" placeholder="Enter your Email" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="password" class="form-control" name="password" placeholder="Enter your Password" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1" checked>
                                            <label class="form-check-label" for="inlineRadio1">Remember Me</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn w-100 mt-3 mt-sm-4" type="submit">Sign In</button>
                                </div>
                                <div class="col-12">
                                    <hr>
                                    <div class="other-option">
                                        <span class="d-block text-center mb-4">Or</span>
                                        <!-- Social Icons -->
                                        <div class="social-icons d-flex justify-content-center">
                                            <a class="facebook" href="#">
                                                <i class="fab fa-facebook-f"></i>
                                                <i class="fab fa-facebook-f"></i>
                                            </a>
                                            <a class="twitter" href="#">
                                                <i class="fab fa-twitter"></i>
                                                <i class="fab fa-twitter"></i>
                                            </a>
                                            <a class="google-plus" href="#">
                                                <i class="fab fa-google-plus-g"></i>
                                                <i class="fab fa-google-plus-g"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Login Area End ***** -->


        <!--====== Modal Responsive Menu Area Start ======-->
        <div id="menu" class="modal fade p-0">
            <div class="modal-dialog dialog-animated">
                <div class="modal-content h-100">
                    <div class="modal-header" data-dismiss="modal">
                        Menu <i class="far fa-times-circle icon-close"></i>
                    </div>
                    <div class="menu modal-body">
                        <div class="row w-100">
                            <div class="items p-0 col-12 text-center"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== Modal Responsive Menu Area End ======-->

        <!--====== Scroll To Top Area Start ======-->
        <div id="scroll-to-top" class="scroll-to-top">
            <a href="#header" class="smooth-anchor">
                <i class="fas fa-arrow-up"></i>
            </a>
        </div>
        <!--====== Scroll To Top Area End ======-->
{% endblock %}

templates/User/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign up {% endblock %}

{% block content %}
        <!-- ***** Breadcrumb Area Start ***** -->
        <section class="breadcrumb-area overlay-dark d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Breamcrumb Content -->
                        <div class="breadcrumb-content text-center">
                            <h2 class="m-0">Signup</h2>
                            <p>{{ form.errors }}</p>
                            <ol class="breadcrumb d-flex justify-content-center">
                                <li class="breadcrumb-item"><a href="{% url 'Homepage:home' %}">Home</a></li>
{#                                <li class="breadcrumb-item"><a href="#">Pages</a></li>#}
                                <li class="breadcrumb-item active">Signup</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Breadcrumb Area End ***** -->

        <!-- ***** Signup Area Start ***** -->
        <section class="author-area">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-8 col-lg-7">
                        <!-- Intro -->
                        <div class="intro text-center">
                            <span>Signup</span>
                            <h3 class="mt-3 mb-0">Create an Account</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae quo ad iste ipsum officiis deleniti asperiores sit.</p>
                        </div>
                        <!-- Item Form -->
                        <form class="item-form card no-hover" method="post" action="{% url 'userprofile:register' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="text" class="form-control" name="first_name" placeholder="Enter your first Name" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="text" class="form-control" name="last_name" placeholder="Enter your last Name" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="number" class="form-control" name="phone" placeholder="Enter your Phone Number" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="email" class="form-control" name="email" placeholder="Enter your Email" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input id="id_password" type="password" class="form-control" name="password1" placeholder="Enter your Password" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input id="id_password" type="password" class="form-control" name="password2" placeholder="Enter your Password" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                                            <label class="form-check-label" for="inlineRadio1">I agree to <a href="#">Privacy Policy</a></label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn w-100 mt-3 mt-sm-4" type="submit">Sign Up</button>
                                </div>
                                <div class="col-12">
                                    <span class="d-block text-center mt-4">Already have an account? <a href="{% url 'userprofile:login' %}">Login</a></span>
                                </div>
                                <div class="col-12">
                                    <hr>
                                    <div class="other-option">
                                        <span class="d-block text-center mb-4">Or</span>
                                        <!-- Social Icons -->
                                        <div class="social-icons d-flex justify-content-center">
                                            <a class="facebook" href="#">
                                                <i class="fab fa-facebook-f"></i>
                                                <i class="fab fa-facebook-f"></i>
                                            </a>
                                            <a class="twitter" href="#">
                                                <i class="fab fa-twitter"></i>
                                                <i class="fab fa-twitter"></i>
                                            </a>
                                            <a class="google-plus" href="#">
                                                <i class="fab fa-google-plus-g"></i>
                                                <i class="fab fa-google-plus-g"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Signup Area End ***** -->

        <!--====== Modal Responsive Menu Area Start ======-->
        <div id="menu" class="modal fade p-0">
            <div class="modal-dialog dialog-animated">
                <div class="modal-content h-100">
                    <div class="modal-header" data-dismiss="modal">
                        Menu <i class="far fa-times-circle icon-close"></i>
                    </div>
                    <div class="menu modal-body">
                        <div class="row w-100">
                            <div class="items p-0 col-12 text-center"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== Modal Responsive Menu Area End ======-->

        <!--====== Scroll To Top Area Start ======-->
        <div id="scroll-to-top" class="scroll-to-top">
            <a href="#header" class="smooth-anchor">
                <i class="fas fa-arrow-up"></i>
            </a>
        </div>
        <!--====== Scroll To Top Area End ======-->

{% endblock %}